### ISSUE TITLE
Unable to set shortcut to grave/tilde

### ISSUE THREAD

**Issue by BlueDrink9** [joedf/Qonsole#13]
I set the shortcut to windows + `,  then save. Opening settings again shows it has changed to R. US keyboard

**Comment by joedf** [comment]
I just tested version 1.4.6 with <kbd>Win</kbd>+<kbd>`</kbd>.
Works fine for me. hmmm ... 🤔 💭 

Send me your settings file? App version? OS info?

**Comment by BlueDrink9** [comment]
Windows 10, just reinstalled OS and still happening. 1903, build 18.352. Latest master commit, not release. Running directly from the .ahk. Happens on a freshly generated settings file, too:

```
[Animation]
Speed=1
Delay=20
dx=25
AnimationDisabled=0
GuiBGDarken_Increment=6
GuiBGDarken_Max=127
GuiBGDarken_Color=0x1A1A1A
[Settings]
HideOnInActive=0
HorizontallyCentered=0
BottomPlaced=0
CmdPaste=1
AutoWinActivate=0
ReduceMemory=1
RunOnStartUp=0
Console_Mode=Cmd
TransparencyPercent=20
CMD_Path=C:\Users\User\Documents\Qonsole\cmd_Qonsole.lnk
OpenHotkey=#`
CMD_Width=1440
CMD_Height=266
CMD_StartUpArgs=
CMD_offset=0
```

I also get this error in a window, with options to abort, ignore or retry, whenever I start the program - retrying will start the console.
```
---------------------------
LibConError
---------------------------
AttachConsole() Failure
Errorlevel: 0
A_LastError: 6

Will now Exit.
---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by BlueDrink9** [comment]
Can confirm the issue occurs with the latest release, too

**Comment by BlueDrink9** [comment]
Hmm... What's curious is I cloned [this repo](https://github.com/lonepie/mintty-quake-console), and it has the same problem.

**Comment by BlueDrink9** [comment]
Manually setting the ini to `#SC029` works

**Comment by joedf** [comment]
Interesting... Thanks for sharing a workaround. I don't think I knew [mintty-quake-console](https://github.com/lonepie/mintty-quake-console) existed... Seems pretty cool 👍 

The "AttachConsole() Failure" occurs for me too occasionally. <strike>I'll open a separate issue.</strike>

Nevermind, see issue #11 😀
