### ISSUE TITLE
Allow any shortcut to open/close the console

### ISSUE THREAD

**Issue by Nowaker** [joedf/Qonsole#16]
I use Alt+\` on Linux and Option-\` on Mac, so it would be great to have the same shortcut on Windows.

Thanks for considering it!

**Comment by joedf** [comment]
I'm not sure what you mean here. Did you mean to have a custom hotkey/binding such as `` Alt + ` ``? If so, you can already do this in the settings window, or by changing the ini file directly by adding ``OpenHotkey=!` `` under the `[Settings]` section.

**Comment by Nowaker** [comment]
Sorry, I didn't escape the \` character! Yes, Alt+\`.

The settings window says `Win + [ active text field ]` so it suggests I can only do shortcuts with Windows key. If it's not a case, the UI needs to be clearer about it.

**Comment by joedf** [comment]
I think the settings UI definitely needs to be reworked... 😅 
... but for now, you can just uncheck the box next to it.

Closing this issue. I've opened a new issue for the settings UI: https://github.com/joedf/Qonsole/issues/18
