### ISSUE TITLE
Windows Taskbar

### ISSUE THREAD

**Issue by gkaravidas** [joedf/Qonsole#3]
Hello!
I'm using a lot your Qonsole and I really like the ease it gives me on my work, though I have a small problem and I don't know if it should be written here, as an issue, or elsewhere.

Anyway, the thing is that I am used to position the windows taskbar on the top of the screen and not on the bottom, as it is by default. For this reason the Qonsole is behaving a bit strange. Maybe a good solution would be to have a setting where to choose the margin from the top/bottom of the screen. In that way I could position the Qonsole immediately under the taskbar and problem solved! What do you think?

Thanks for your time

**Comment by joedf** [comment]
So a "vertical margin" option? I could add that, no issue. :)
If you could also provide a screenshot, it would be easier for me to visualise it. 👍

**Comment by gkaravidas** [comment]
Well of course I can give a screenshot, though it's not very clear what the problem is. If you notice, you can see the taskbar covering part of the Qonsole on the top.

![screenshot 1](https://cloud.githubusercontent.com/assets/13132336/23012902/0579f884-f431-11e6-8ffd-f9e6de6e5289.png)

**Comment by joedf** [comment]
I see qonsole seems to appear behind the taskbar... Usually, it is in front of it (set as AlwaysOnTop). Hmm...

**Comment by joedf** [comment]
Hopefully, this new release is satisfactory. :)
> [Qonsole v1.4.4](https://github.com/joedf/Qonsole/releases/tag/v1.4.4)

**Comment by gkaravidas** [comment]
It's not perfect, or well polished, f.e. the animation in the beginning makes the qonsole pass in front of the taskbar, since it starts from the top of the screen and it looks a bit ugly, but it does the trick and it works fine.

Thanks joedf!
