### ISSUE TITLE
Missing documentation about using wsltty with 

### ISSUE THREAD

**Issue by 07pepa** [joedf/Qonsole#7]
This project already support wsltty..... tested it.... everything you need to do is to rewrite cmd_Qonsole link to
%LOCALAPPDATA%\wsltty\bin\mintty.exe --WSL="Ubuntu-18.04" --configdir="%APPDATA%\wsltty" -~

and it works.....

**Comment by joedf** [comment]
Qonsole was written in a "pseudo-generic" way. I had the idea of providing partial support for the many different console applications out there, but there are so many. Thanks for writing this here for other users to see. I have not tested it with wsltty.
