### ISSUE TITLE
Detects as Trojan

### ISSUE THREAD

**Issue by cyberhck** [joedf/Qonsole#9]
The release when extracted and scanned, virustotal detects it as Trojan, can someone have a look?

**Comment by joedf** [comment]
This is a false positive with AutoHotkey executables. There isn't much I can do then maybe make a complete rewrite in a different language. There is so much about this out there:
https://www.google.com/search?q=autohotkey+false+positive

**Comment by cyberhck** [comment]
how does electron does it then? I know it only works when electron app is actually running, but that also should be okay, right? Maybe a different version just for that? My company doesn't let me run Qonsole because of this 🙁

**Comment by joedf** [comment]
Electron interferes with qonsole? can you install autohotkey? maybe you can run it from source?

**Comment by cyberhck** [comment]
No, I mean electron also adds hot key kind of thing, except electron app should be running in order to use the hot key.

**Comment by joedf** [comment]
Electron runs on top of Node.js to handle any system functions, hotkeys, etc.
Qonsole runs on top of AutoHotkey...

**Comment by cyberhck** [comment]
got it, there's nothing we can do about this.
